import PDFDocument from 'pdfkit';

// Palette
const BG = '#0b1020';
const PANEL = '#141c34';
const TRACK = '#1e2740';
const TEXT = '#e8ecf6';
const MUTED = '#8592ad';
const FAINT = '#5b6787';
const ACCENT = '#6366f1';
const CYAN = '#22d3ee';
const LINE = '#232b45';

const trunc = (s, n) => { const t = String(s ?? ''); return t.length > n ? `${t.slice(0, n - 1)}…` : t; };

// Render a dark, single-page executive report to a PDF Buffer.
export function buildExecutivePdf(summary, { title = 'Cash Horizon', subtitle = 'Executive Report' } = {}) {
    return new Promise((resolve, reject) => {
        const doc = new PDFDocument({ size: 'A4', margin: 0 });
        const chunks = [];
        doc.on('data', (c) => chunks.push(c));
        doc.on('end', () => resolve(Buffer.concat(chunks)));
        doc.on('error', reject);

        const W = doc.page.width;      // 595.28
        const H = doc.page.height;     // 841.89
        const M = 40;
        const CW = W - M * 2;          // content width
        const date = new Date().toISOString().slice(0, 10);

        // ---- background ----
        doc.rect(0, 0, W, H).fill(BG);

        // ---- header band with gradient ----
        const hg = doc.linearGradient(0, 0, W, 100);
        hg.stop(0, '#4f46e5').stop(0.55, '#4338ca').stop(1, '#0891b2');
        doc.rect(0, 0, W, 100).fill(hg);
        // agent mark: rounded square + a vector diamond (NEO glyph, no font dependency)
        doc.save();
        doc.fillOpacity(0.16).roundedRect(M, 30, 40, 40, 11).fill('#ffffff');
        doc.restore();
        const mx = M + 20;
        const my = 50;
        const r = 9;
        doc.polygon([mx, my - r], [mx + r, my], [mx, my + r], [mx - r, my]).fill('#ffffff');
        doc.fillColor('#ffffff').font('Helvetica-Bold').fontSize(21).text(title, M + 54, 32);
        doc.fillColor('#dbe4ff').font('Helvetica').fontSize(9).text(`${subtitle.toUpperCase()}  ·  GENERATED BY NEO`, M + 54, 60, { characterSpacing: 1 });
        doc.fillColor('#c7d2fe').fontSize(8.5).text(date, M, 38, { width: CW, align: 'right' });

        // ---- KPI tiles ----
        const kpiY = 122;
        const gap = 12;
        const tileW = (CW - gap * 3) / 4;
        const tileH = 66;
        (summary.kpis || []).slice(0, 4).forEach((k, i) => {
            const x = M + i * (tileW + gap);
            doc.roundedRect(x, kpiY, tileW, tileH, 9).fill(PANEL);
            doc.roundedRect(x, kpiY, tileW, 3, 1.5).fill(k.color || ACCENT);
            doc.fillColor(MUTED).font('Helvetica').fontSize(6.8).text(String(k.label).toUpperCase(), x + 10, kpiY + 12, { width: tileW - 20, characterSpacing: 0.4 });
            doc.fillColor(TEXT).font('Helvetica-Bold').fontSize(13).text(trunc(k.value, 16), x + 10, kpiY + 26, { width: tileW - 16, lineBreak: false });
            doc.fillColor(FAINT).font('Helvetica').fontSize(6.8).text(trunc(k.hint, 20), x + 10, kpiY + 48, { width: tileW - 16, lineBreak: false });
        });

        // ---- section label helper ----
        const sectionLabel = (x, y, label, color = ACCENT) => {
            doc.roundedRect(x, y + 1, 3, 11, 1.5).fill(color);
            doc.fillColor('#aeb8d4').font('Helvetica-Bold').fontSize(8.5).text(String(label).toUpperCase(), x + 9, y, { characterSpacing: 0.6 });
            return y + 20;
        };
        const bullet = (x, y, text, w, color = ACCENT) => {
            doc.circle(x + 2, y + 4, 1.6).fill(color);
            doc.fillColor('#c3cbe0').font('Helvetica').fontSize(8.5).text(text, x + 10, y, { width: w - 10, lineGap: 1.5 });
            return doc.y + 4;
        };

        // ---- pipeline by stage (bars) ----
        let y = kpiY + tileH + 22;
        y = sectionLabel(M, y, 'Pipeline by stage', CYAN);
        const barLabelW = 78;
        const trackX = M + barLabelW + 6;
        const trackW = 300;
        const max = summary.maxStageWeighted || 1;
        const pipeline = (summary.pipeline || []).slice(0, 5);
        if (!pipeline.length) {
            doc.fillColor(FAINT).font('Helvetica').fontSize(9).text('No open prospects.', M, y);
            y += 18;
        }
        pipeline.forEach((p) => {
            doc.fillColor(TEXT).font('Helvetica').fontSize(8.5).text(`${p.stage}`, M, y + 1, { width: barLabelW });
            doc.fillColor(FAINT).fontSize(7).text(`${p.count} deal${p.count > 1 ? 's' : ''}`, M, y + 12, { width: barLabelW });
            doc.roundedRect(trackX, y, trackW, 11, 5.5).fill(TRACK);
            const w = Math.max(8, (p.weighted / max) * trackW);
            const bg = doc.linearGradient(trackX, 0, trackX + trackW, 0);
            bg.stop(0, ACCENT).stop(1, CYAN);
            doc.roundedRect(trackX, y, w, 11, 5.5).fill(bg);
            doc.fillColor('#cbd5e1').font('Helvetica-Bold').fontSize(8).text(p.weightedStr, trackX + trackW + 10, y + 1, { width: CW - (trackX + trackW + 10 - M), lineBreak: false });
            y += 24;
        });

        // ---- two columns ----
        const colTop = y + 12;
        const colW = (CW - 30) / 2;
        const leftX = M;
        const rightX = M + colW + 30;

        // left: needs attention + meddicc gaps
        let ly = sectionLabel(leftX, colTop, 'Needs attention', '#f87171');
        const attention = (summary.attention || []).slice(0, 4);
        if (!attention.length) ly = bullet(leftX, ly, 'Nothing flagged — portfolio is healthy.', colW, '#34d399');
        attention.forEach((a) => {
            const line = a.value ? `${a.name} — ${a.tag}, ${a.value}${a.owner ? ` (${a.owner})` : ''}` : `${a.name} — ${a.tag}`;
            ly = bullet(leftX, ly, trunc(line, 62), colW, '#f87171');
        });
        ly += 8;
        ly = sectionLabel(leftX, ly, 'MEDDICC gaps', '#fbbf24');
        const weak = (summary.weak || []).slice(0, 3);
        if (!weak.length) ly = bullet(leftX, ly, 'All open prospects are 3+/7 qualified.', colW, '#34d399');
        weak.forEach((wk) => { ly = bullet(leftX, ly, `${trunc(wk.name, 34)} — ${wk.score}/7 (${wk.stage})`, colW, '#fbbf24'); });

        // right: partner contribution + overview
        let ry = sectionLabel(rightX, colTop, 'Partner contribution', '#38bdf8');
        const partners = (summary.partners || []).slice(0, 4);
        if (!partners.length) ry = bullet(rightX, ry, 'No partner-sourced deals yet.', colW, '#38bdf8');
        partners.forEach((p) => { ry = bullet(rightX, ry, `${trunc(p.name, 28)} — ${p.sourced} sourced, ${p.closed} closed`, colW, '#38bdf8'); });
        ry += 8;
        ry = sectionLabel(rightX, ry, 'Overview', ACCENT);
        doc.fillColor('#b6bfd8').font('Helvetica').fontSize(8.5).text(summary.narrative || '', rightX, ry, { width: colW, lineGap: 2 });

        // ---- recommended actions box ----
        const boxY = Math.max(ly, doc.y) + 20;
        const actions = (summary.actions || []).slice(0, 4);
        const boxH = 34 + actions.length * 18;
        doc.roundedRect(M, boxY, CW, boxH, 12).fill('#101830');
        doc.roundedRect(M, boxY, 4, boxH, 2).fill(ACCENT);
        doc.fillColor('#e8ecf6').font('Helvetica-Bold').fontSize(9).text('RECOMMENDED ACTIONS', M + 18, boxY + 12, { characterSpacing: 0.6 });
        let ay = boxY + 30;
        actions.forEach((a, i) => {
            doc.fillColor(CYAN).font('Helvetica-Bold').fontSize(8.5).text(`${i + 1}`, M + 18, ay, { width: 12 });
            doc.fillColor('#c3cbe0').font('Helvetica').fontSize(8.5).text(trunc(a, 118), M + 32, ay, { width: CW - 46, lineBreak: false });
            ay += 18;
        });

        // ---- footer ----
        doc.rect(0, H - 28, W, 28).fill('#0a0e1c');
        doc.fillColor(FAINT).font('Helvetica').fontSize(7.5).text(`Summary generated by ${summary.generatedBy || 'Cash Horizon'}  ·  Confidential  ·  ${date}`, M, H - 20, { width: CW, align: 'center' });

        doc.end();
    });
}
