import PDFDocument from 'pdfkit';

// Palette
const BG = '#0b1020';
const PANEL = '#141c34';
const TRACK = '#1e2740';
const TEXT = '#e8ecf6';
const MUTED = '#8592ad';
const FAINT = '#5b6787';
const ACCENT = '#6366f1';
const CYAN = '#22d3ee';

const trunc = (s, n) => { const t = String(s ?? ''); return t.length > n ? `${t.slice(0, n - 1)}…` : t; };

// Generic dark, single-page executive report. `summary` is module-agnostic:
//   { kpis:[{label,value,hint,color}], bars:{title,items:[{label,sub,value,valueStr}]},
//     sections:[{title,color,lines:[]}], actions:[], generatedBy }
export function buildExecutivePdf(summary, { title = 'Report', subtitle = 'Executive Report' } = {}) {
    return new Promise((resolve, reject) => {
        const doc = new PDFDocument({ size: 'A4', margin: 0 });
        const chunks = [];
        doc.on('data', (c) => chunks.push(c));
        doc.on('end', () => resolve(Buffer.concat(chunks)));
        doc.on('error', reject);

        const W = doc.page.width;
        const H = doc.page.height;
        const M = 40;
        const CW = W - M * 2;
        const date = new Date().toISOString().slice(0, 10);

        doc.rect(0, 0, W, H).fill(BG);

        // header
        const hg = doc.linearGradient(0, 0, W, 100);
        hg.stop(0, '#4f46e5').stop(0.55, '#4338ca').stop(1, '#0891b2');
        doc.rect(0, 0, W, 100).fill(hg);
        doc.save();
        doc.fillOpacity(0.16).roundedRect(M, 30, 40, 40, 11).fill('#ffffff');
        doc.restore();
        const mx = M + 20, my = 50, r = 9;
        doc.polygon([mx, my - r], [mx + r, my], [mx, my + r], [mx - r, my]).fill('#ffffff');
        doc.fillColor('#ffffff').font('Helvetica-Bold').fontSize(21).text(title, M + 54, 32);
        doc.fillColor('#dbe4ff').font('Helvetica').fontSize(9).text(`${subtitle.toUpperCase()}  ·  GENERATED BY NEO`, M + 54, 60, { characterSpacing: 1 });
        doc.fillColor('#c7d2fe').fontSize(8.5).text(date, M, 38, { width: CW, align: 'right' });

        // KPI tiles
        const kpiY = 122;
        const gap = 12;
        const tileW = (CW - gap * 3) / 4;
        const tileH = 66;
        (summary.kpis || []).slice(0, 4).forEach((k, i) => {
            const x = M + i * (tileW + gap);
            doc.roundedRect(x, kpiY, tileW, tileH, 9).fill(PANEL);
            doc.roundedRect(x, kpiY, tileW, 3, 1.5).fill(k.color || ACCENT);
            doc.fillColor(MUTED).font('Helvetica').fontSize(6.8).text(String(k.label).toUpperCase(), x + 10, kpiY + 12, { width: tileW - 20, characterSpacing: 0.4 });
            doc.fillColor(TEXT).font('Helvetica-Bold').fontSize(13).text(trunc(k.value, 16), x + 10, kpiY + 26, { width: tileW - 16, lineBreak: false });
            doc.fillColor(FAINT).font('Helvetica').fontSize(6.8).text(trunc(k.hint, 22), x + 10, kpiY + 48, { width: tileW - 16, lineBreak: false });
        });

        const sectionLabel = (x, y, label, color = ACCENT) => {
            doc.roundedRect(x, y + 1, 3, 11, 1.5).fill(color);
            doc.fillColor('#aeb8d4').font('Helvetica-Bold').fontSize(8.5).text(String(label).toUpperCase(), x + 9, y, { characterSpacing: 0.6 });
            return y + 20;
        };
        const bullet = (x, y, text, w, color) => {
            doc.circle(x + 2, y + 4, 1.6).fill(color);
            doc.fillColor('#c3cbe0').font('Helvetica').fontSize(8.5).text(text, x + 10, y, { width: w - 10, lineGap: 1.5 });
            return doc.y + 4;
        };

        // bars
        let y = kpiY + tileH + 22;
        const bars = summary.bars || { title: '', items: [] };
        y = sectionLabel(M, y, bars.title || 'Breakdown', CYAN);
        const barLabelW = 92;
        const trackX = M + barLabelW + 6;
        const trackW = 290;
        const max = Math.max(1, ...bars.items.map((b) => b.value || 0));
        if (!bars.items.length) { doc.fillColor(FAINT).font('Helvetica').fontSize(9).text('No data.', M, y); y += 18; }
        bars.items.slice(0, 5).forEach((b) => {
            doc.fillColor(TEXT).font('Helvetica').fontSize(8.5).text(b.label, M, y + 1, { width: barLabelW });
            if (b.sub) doc.fillColor(FAINT).fontSize(7).text(b.sub, M, y + 12, { width: barLabelW });
            doc.roundedRect(trackX, y, trackW, 11, 5.5).fill(TRACK);
            const w = Math.max(8, ((b.value || 0) / max) * trackW);
            const bg = doc.linearGradient(trackX, 0, trackX + trackW, 0);
            bg.stop(0, ACCENT).stop(1, CYAN);
            doc.roundedRect(trackX, y, w, 11, 5.5).fill(bg);
            doc.fillColor('#cbd5e1').font('Helvetica-Bold').fontSize(8).text(b.valueStr || '', trackX + trackW + 10, y + 1, { width: CW - (trackX + trackW + 10 - M), lineBreak: false });
            y += 24;
        });

        // two-column sections (up to 4)
        const colTop = y + 12;
        const colW = (CW - 30) / 2;
        const cols = [M, M + colW + 30];
        const colY = [colTop, colTop];
        (summary.sections || []).slice(0, 4).forEach((sec, i) => {
            const ci = i % 2;
            let sy = sectionLabel(cols[ci], colY[ci], sec.title, sec.color || ACCENT);
            const lines = sec.lines && sec.lines.length ? sec.lines : ['—'];
            lines.slice(0, 5).forEach((ln) => { sy = bullet(cols[ci], sy, trunc(ln, 64), colW, sec.color || ACCENT); });
            colY[ci] = sy + 8;
        });

        // actions box
        const boxY = Math.max(colY[0], colY[1]) + 12;
        const actions = (summary.actions || []).slice(0, 4);
        const boxH = 34 + actions.length * 18;
        doc.roundedRect(M, boxY, CW, boxH, 12).fill('#101830');
        doc.roundedRect(M, boxY, 4, boxH, 2).fill(ACCENT);
        doc.fillColor('#e8ecf6').font('Helvetica-Bold').fontSize(9).text('RECOMMENDED ACTIONS', M + 18, boxY + 12, { characterSpacing: 0.6 });
        let ay = boxY + 30;
        actions.forEach((a, i) => {
            doc.fillColor(CYAN).font('Helvetica-Bold').fontSize(8.5).text(`${i + 1}`, M + 18, ay, { width: 12 });
            doc.fillColor('#c3cbe0').font('Helvetica').fontSize(8.5).text(trunc(a, 118), M + 32, ay, { width: CW - 46, lineBreak: false });
            ay += 18;
        });

        // footer
        doc.rect(0, H - 28, W, 28).fill('#0a0e1c');
        doc.fillColor(FAINT).font('Helvetica').fontSize(7.5).text(`Summary generated by ${summary.generatedBy || 'Cash Horizon'}  ·  Confidential  ·  ${date}`, M, H - 20, { width: CW, align: 'center' });

        doc.end();
    });
}
